# Generated by Django 3.1.7 on 2021-05-07 06:03

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
    ]
